### ISSUE TITLE
Null reference exception when using UriImageSource 

### ISSUE THREAD

**Issue by JosueDM94** [roubachof/Maui.Nuke#3]
**Description**
UriImageSource is not displayed when using Nuke package.

**Steps to Reproduce**

1. Create a new MAUI app with the default template
2. Add Nuget Sharpnado.Maui.Nuke
3. Initialize Nuke as described in Maui.Nuke
4. Add an Image control with a Uri Source
`<Image
        Aspect="Fill"
        WidthRequest="162"
        HeightRequest="162">
        <Image.Source>
            <UriImageSource
                CacheValidity="1"
                CachingEnabled="True"
                Uri="https://en.wikipedia.org/wiki/Image#/media/File:Image_created_with_a_mobile_phone.png"/>
        </Image.Source>
    </Image>`
6. You won't see the image displayed

**Affected platforms**
iOS

**Did you find any workaround?**
nope

**Version with bug**
10.11.2

**Application Output**
```
Microsoft.Maui.UriImageSourceService: Information: Loading "https://en.wikipedia.org/wiki/Image#/media/File:Image_created_with_a_mobile_phone.png" as a web URL
Microsoft.Maui.UriImageSourceService: Error: Fail to load image: https://en.wikipedia.org/wiki/Image#/media/File:Image_created_with_a_mobile_phone.png

System.NullReferenceException: Object reference not set to an instance of an object.
   at Maui.Nuke.NukeController.LoadImageAsync(NSUrl url, Action`1 onFail)
   at Maui.Nuke.NukeUriImageSourceService.GetImageAsync(IImageSource imageSource, Single scale, CancellationToken cancellationToken)
Microsoft.Maui.UriImageSourceService: Information: Loading "https://en.wikipedia.org/wiki/Image#/media/File:Image_created_with_a_mobile_phone.png" as a web URL
Microsoft.Maui.UriImageSourceService: Error: Fail to load image: https://en.wikipedia.org/wiki/Image#/media/File:Image_created_with_a_mobile_phone.png
```

**Anything else?**
Thanks in advance for this AMAZING library!

**Comment by nanthakumaran-s** [comment]
Hi @JosueDM94, Are you having any workaround to make this work? I'm also facing this issue.

**Comment by nanthakumaran-s** [comment]
I have initialised and getting this same issue.

**Comment by JosueDM94** [comment]
Hey @nanthakumaran-s, I haven't found a workaround for UriImageSource, I just removed NukeUriImageSourceService from the container and used FFImageLoading.Compat.

@roubachof the library was initialized

**Comment by roubachof** [comment]
fixed in v12.8
