### ISSUE TITLE
Cannot use the library in Release builds

### ISSUE THREAD

**Issue by plequere-ms** [roubachof/Maui.Nuke#5]
Hello,

First, many thanks for a great library. It's very simple to use and it works perfectly in Debug builds.

However, I'm unable to build in Release mode. I am consistently hitting the following issue, and rebuilding/cleaning did not help.

`Microsoft.Common.CurrentVersion.targets(4862,5): warning MSB3026: Could not copy "C:\Users\patri\.nuget\packages\imagecaching.nuke\2.0.13\lib\net6.0-ios16.1\ImageCaching.Nuke.resources\NukeProxy.xcframework\ios-arm64_x86_64-simulator\NukeProxy.framework\Modules\NukeProxy.swiftmodule\x86_64-apple-ios-simulator.private.swiftinterface" to "bin\Release\net7.0-ios\iossimulator-x64\ImageCaching.Nuke.resources\NukeProxy.xcframework\ios-arm64_x86_64-simulator\NukeProxy.framework\Modules\NukeProxy.swiftmodule\x86_64-apple-ios-simulator.private.swiftinterface". Beginning retry 1 in 1000ms. Could not find a part of the path 'bin\Release\net7.0-ios\iossimulator-x64\ImageCaching.Nuke.resources\NukeProxy.xcframework\ios-arm64_x86_64-simulator\NukeProxy.framework\Modules\NukeProxy.swiftmodule\x86_64-apple-ios-simulator.private.swiftinterface'.`

Please let me know what you need in order to investigate this issue. Thanks!

**Comment by roubachof** [comment]
I think the Nuke proxy doesn't support release compilation for the simulator. But you should be fine with a real device !

**Comment by tolgraven** [comment]
Installed straight:

```
Installed Sharpnado.Maui.Nuke 10.11.2 from https://api.nuget.org/v3/index.json with content hash h9W4OZFkbupNn2yDXwWp7QtcKEX+MzCZSpKhypsmvWVXlFCjY/lxcOy37hMVJmD6uV9fRzSp/hq7Zc6rvSX47w==.
##[error]The nuget command failed with exit code(1) and error(Could not find a part of the path 'C:\Users\ContainerAdministrator\.nuget\packages\imagecaching.nuke\2.0.13\lib\net6.0-ios16.1\ImageCaching.Nuke.resources\NukeProxy.xcframework\ios-arm64_x86_64-simulator\NukeProxy.framework\Modules\NukeProxy.swiftmodule\arm64-apple-ios-simulator.private.swiftinterface'.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\ContainerAdministrator\.nuget\packages\imagecaching.nuke\2.0.13\lib\net6.0-ios16.1\ImageCaching.Nuke.resources\NukeProxy.xcframework\ios-arm64_x86_64-simulator\NukeProxy.framework\Modules\NukeProxy.swiftmodule\arm64-apple-ios-simulator.private.swiftinterface'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
[...]
```

When also implicitly including imagecaching.nuke:

```
##[error]The nuget command failed with exit code(1) and error(Could not find a part of the path 'C:\Users\ContainerAdministrator\.nuget\packages\imagecaching.nuke\2.0.13\lib\net6.0-ios16.1\ImageCaching.Nuke.resources\NukeProxy.xcframework\ios-arm64_x86_64-simulator\NukeProxy.framework\Modules\NukeProxy.swiftmodule\arm64-apple-ios-simulator.private.swiftinterface'.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\ContainerAdministrator\.nuget\packages\imagecaching.nuke\2.0.13\lib\net6.0-ios16.1\ImageCaching.Nuke.resources\NukeProxy.xcframework\ios-arm64_x86_64-simulator\NukeProxy.framework\Modules\NukeProxy.swiftmodule\arm64-apple-ios-simulator.private.swiftinterface'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
```


In our monorepo release pipeline. Why it even tries to restore the package in the first place when the build is very much not TargetFramework -ios (as guarded against in csproj) or even actually Maui at all (got a separate pipeline for that), I don't understand...
